apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: MSiOT_Test
      defaultBucket: MSiOT_Test_db
      tlsSkipVerify: true
    secureJsonData:
      token: G88GaTn630LBGq_2sozKXJ9Rtru845Pf3pZoQXoKcfUVNwE9ghHywsS5WO7s93phZAQg7HM_cXuXGDwC1uGR3Q==
    isDefault: true
    editable: true
