# Telegraf configuration for ChirpStack - InfluxDB v2
# Subscribes to ChirpStack uplink events on MQTT and writes to InfluxDB

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "10s"
  flush_jitter = "0s"
  omit_hostname = true

# Output: InfluxDB v2
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUXDB_ADMIN_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket = "${INFLUXDB_BUCKET}"

# Input: ChirpStack uplink events via MQTT
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]

  ## Subscribe to all uplink events across all applications and devices
  topics = [
    "application/+/device/+/event/+",
    "application/+/device/+/command/+"
  ]

  topic_tag = "topic"
  client_id = "telegraf-chirpstack-01"
  persistent_session = false
  qos = 0

  data_format = "json"

  # json_time_key = "time"
  # json_time_key = "rxInfo_0_nsTime"
  json_time_format = "2006-01-02T15:04:05.999999999Z07:00"

  ## Tag extraction from JSON payload
 
  json_string_fields = [
    "deviceInfo_deviceName",
    "deduplicationId",
    "devAddr",
    "regionConfigId",
    "confirmed",
    "object_firmware_version",
    "rxInfo_0_gatewayId",
    "rxInfo_1_gatewayId",
    "rxInfo_0_nsTime"
  ]
  ## tags = ["deduplicationId"]

# [[processors.dedup]]
#   dedup_interval = "600s"

## Drop repeated identical measurements within 10 minutes
